/**
 * BondPay Payment Gateway Utility
 *
 * Handles MD5 signature generation and order creation for the BondPay
 * Collection (Payin) API. Server-side only — never import from client components.
 *
 * Signature formula (per BondPay docs):
 *   md5( merchant_id + amount + merchant_order_no + api_key + callback_url )
 */

import { createHash } from 'crypto'

const BONDPAY_API_BASE = 'https://api.bond-payss.com'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface BondPayOrderParams {
  /** INR amount (will be formatted to 2 decimal places) */
  amount: number
  /** Unique order reference generated by our system */
  merchantOrderNo: string
}

export interface BondPayOrderResult {
  success: boolean
  /** URL to redirect the user to for payment */
  payment_url?: string
  /** BondPay's internal order ID */
  order_no?: string
  /** Human-readable message from the gateway */
  message?: string
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Generates the MD5 signature required by BondPay.
 * Concatenates: merchant_id + amount + merchant_order_no + api_key + callback_url
 * then returns the lowercase hex MD5 digest.
 */
export function generateBondPaySignature(
  merchantId: string,
  amount: string,
  merchantOrderNo: string,
  apiKey: string,
  callbackUrl: string,
): string {
  const raw = `${merchantId}${amount}${merchantOrderNo}${apiKey}${callbackUrl}`
  return createHash('md5').update(raw, 'utf8').digest('hex')
}

// ---------------------------------------------------------------------------
// API Call
// ---------------------------------------------------------------------------

/**
 * Creates a BondPay payment order.
 *
 * @returns BondPayOrderResult with success flag and payment_url on success.
 */
export async function createBondPayOrder(
  params: BondPayOrderParams,
): Promise<BondPayOrderResult> {
  const merchantId = process.env.BONDPAY_MERCHANT_ID
  const apiKey = process.env.BONDPAY_API_KEY
  const callbackUrl = process.env.BONDPAY_CALLBACK_URL

  if (!merchantId || !apiKey || !callbackUrl) {
    console.error('[BondPay] Missing required environment variables: BONDPAY_MERCHANT_ID, BONDPAY_API_KEY, or BONDPAY_CALLBACK_URL')
    return {
      success: false,
      message: 'Payment gateway is not configured. Contact support.',
    }
  }

  // Format amount to exactly 2 decimal places as required by BondPay
  const formattedAmount = params.amount.toFixed(2)

  const signature = generateBondPaySignature(
    merchantId,
    formattedAmount,
    params.merchantOrderNo,
    apiKey,
    callbackUrl,
  )

  const payload = {
    merchant_id: merchantId,
    api_key: apiKey,
    amount: formattedAmount,
    merchant_order_no: params.merchantOrderNo,
    callback_url: callbackUrl,
    extra: 0,
    signature,
  }

  try {
    const response = await fetch(`${BONDPAY_API_BASE}/v1/create`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(payload),
      // Abort after 15 seconds to avoid hanging Lambda/Edge functions
      signal: AbortSignal.timeout(15_000),
    })

    const raw = await response.text()
    let json: Record<string, any>

    try {
      json = JSON.parse(raw)
    } catch {
      console.error('[BondPay] Non-JSON response from gateway:', raw)
      return {
        success: false,
        message: `Gateway returned unexpected response (HTTP ${response.status}).`,
      }
    }

    if (!response.ok) {
      console.error('[BondPay] Gateway error response:', json)
      return {
        success: false,
        message: json?.message || json?.msg || `Gateway error (HTTP ${response.status}).`,
      }
    }

    // BondPay success response shape (adapt field names if their API differs):
    // { code: 200, data: { paymentUrl: "...", orderNo: "..." }, message: "success" }
    const data = json?.data || json
    const paymentUrl: string | undefined =
      data?.paymentUrl ?? data?.payment_url ?? data?.pay_url ?? data?.url

    const orderNo: string | undefined =
      data?.orderNo ?? data?.order_no ?? data?.orderId

    if (!paymentUrl) {
      console.error('[BondPay] No payment URL in response:', json)
      return {
        success: false,
        message: 'Gateway did not return a payment URL. Please try again.',
      }
    }

    return {
      success: true,
      payment_url: paymentUrl,
      order_no: orderNo,
      message: json?.message ?? 'Order created successfully.',
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    console.error('[BondPay] Network/fetch error:', message)
    return {
      success: false,
      message: `Could not reach payment gateway: ${message}`,
    }
  }
}
